-- Script SQL de Inicialização do Supabase para LouvorEscala

-- 1. Criar tabela de membros
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  default_role TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criar tabela de cultos (services)
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  church TEXT NOT NULL,
  date DATE NOT NULL,
  day_time TEXT NOT NULL,
  title TEXT NOT NULL,
  week_num INT DEFAULT 1
);

-- 3. Criar tabela de disponibilidade
CREATE TABLE IF NOT EXISTS public.availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT REFERENCES public.services(id) ON DELETE CASCADE,
  member_name TEXT NOT NULL,
  role TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Criar tabela de escala (schedule)
CREATE TABLE IF NOT EXISTS public.schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT UNIQUE REFERENCES public.services(id) ON DELETE CASCADE,
  keyboard_member TEXT DEFAULT '-',
  guitar_member TEXT DEFAULT '-',
  bass_member TEXT DEFAULT '-',
  drums_member TEXT DEFAULT '-',
  vocal_members TEXT DEFAULT '-',
  published INT DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Criar tabela de histórico de trocas (swap_logs)
CREATE TABLE IF NOT EXISTS public.swap_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT REFERENCES public.services(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  old_member TEXT NOT NULL,
  new_member TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security) e liberar permissões públicas para desenvolvimento
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swap_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura publica em members" ON public.members FOR SELECT USING (true);
CREATE POLICY "Permitir insercao publica em members" ON public.members FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir atualizacao publica em members" ON public.members FOR UPDATE USING (true);

CREATE POLICY "Permitir leitura publica em services" ON public.services FOR SELECT USING (true);
CREATE POLICY "Permitir insercao publica em services" ON public.services FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir leitura publica em availability" ON public.availability FOR SELECT USING (true);
CREATE POLICY "Permitir insercao publica em availability" ON public.availability FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir exclusao publica em availability" ON public.availability FOR DELETE USING (true);

CREATE POLICY "Permitir leitura publica em schedule" ON public.schedule FOR SELECT USING (true);
CREATE POLICY "Permitir insercao e atualizacao publica em schedule" ON public.schedule FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir update publico em schedule" ON public.schedule FOR UPDATE USING (true);

CREATE POLICY "Permitir leitura publica em swap_logs" ON public.swap_logs FOR SELECT USING (true);
CREATE POLICY "Permitir insercao publica em swap_logs" ON public.swap_logs FOR INSERT WITH CHECK (true);

-- Dados Iniciais (Seeds)

-- Inserir Membros
INSERT INTO public.members (name, default_role) VALUES
  ('JEREMIAS', 'Baixo'),
  ('JUNIOR', 'Baixo'),
  ('PAULO ROBERTO', 'Violão'),
  ('RENE', 'Teclado'),
  ('GABRIEL', 'Teclado'),
  ('LAERTE', 'Teclado'),
  ('RODRIGO', 'Bateria'),
  ('JAILSON', 'Bateria'),
  ('HELDER', 'Bateria'),
  ('STANLEY', 'Bateria'),
  ('GABRIELZINHO', 'Bateria'),
  ('EMERSON', 'Baixo'),
  ('ISRAEL', 'Baixo'),
  ('MIZAEL', 'Baixo'),
  ('OTONIEL', 'Violão'),
  ('XANDY', 'Violão'),
  ('KAIO', 'Baixo'),
  ('CHARLES', 'Bateria'),
  ('JOSELITO', 'Violão'),
  ('FABI', 'Vocal'),
  ('KELLY', 'Vocal'),
  ('JESSIKA', 'Vocal'),
  ('RHAYZA', 'Vocal'),
  ('GISELE', 'Vocal'),
  ('LEIDIANE', 'Vocal'),
  ('VANDERLANE', 'Vocal'),
  ('BARBARA', 'Vocal'),
  ('LIA', 'Vocal'),
  ('FRANCINALDO', 'Vocal'),
  ('SARA', 'Vocal'),
  ('LUIZA', 'Vocal'),
  ('EVELINE', 'Vocal'),
  ('ADNA', 'Vocal'),
  ('FABIELLE', 'Vocal'),
  ('ANDREIA', 'Vocal'),
  ('DAIANA', 'Vocal'),
  ('LUCAS BASTOS', 'Vocal')
ON CONFLICT (name) DO NOTHING;

-- Inserir Cultos de Agosto 2026
INSERT INTO public.services (church, date, day_time, title, week_num) VALUES
  ('Itaperi',    '2026-07-29', 'QUARTA 19:30',  'CULTO DA PALAVRA ITAPERI',    1),
  ('Industrial', '2026-07-30', 'QUINTA 19:30',  'CULTO DA PALAVRA INDUSTRIAL', 1),
  ('Industrial', '2026-08-02', 'DOMINGO 10:00', 'CULTO INDUSTRIAL (MANHÃ)',    1),
  ('Industrial', '2026-08-02', 'DOMINGO 17:00', 'CULTO INDUSTRIAL (TARDE)',    1),
  ('Industrial', '2026-08-02', 'DOMINGO 19:00', 'CULTO INDUSTRIAL (NOITE)',    1),
  ('Itaperi',    '2026-08-02', 'DOMINGO 18:00', 'CULTO ITAPERI (NOITE)',       1),

  ('Itaperi',    '2026-08-05', 'QUARTA 19:30',  'CULTO DA PALAVRA ITAPERI',    2),
  ('Industrial', '2026-08-06', 'QUINTA 19:30',  'CULTO DA PALAVRA INDUSTRIAL', 2),
  ('Industrial', '2026-08-09', 'DOMINGO 10:00', 'CULTO INDUSTRIAL (MANHÃ)',    2),
  ('Industrial', '2026-08-09', 'DOMINGO 17:00', 'CULTO INDUSTRIAL (TARDE)',    2),
  ('Industrial', '2026-08-09', 'DOMINGO 19:00', 'CULTO INDUSTRIAL (NOITE)',    2),
  ('Itaperi',    '2026-08-09', 'DOMINGO 18:00', 'CULTO ITAPERI (NOITE)',       2),

  ('Itaperi',    '2026-08-12', 'QUARTA 19:30',  'CULTO DA PALAVRA ITAPERI',    3),
  ('Industrial', '2026-08-13', 'QUINTA 19:30',  'CULTO DA PALAVRA INDUSTRIAL', 3),
  ('Industrial', '2026-08-16', 'DOMINGO 10:00', 'CULTO INDUSTRIAL (MANHÃ)',    3),
  ('Industrial', '2026-08-16', 'DOMINGO 17:00', 'CULTO INDUSTRIAL (TARDE)',    3),
  ('Industrial', '2026-08-16', 'DOMINGO 19:00', 'CULTO INDUSTRIAL (NOITE)',    3),
  ('Itaperi',    '2026-08-16', 'DOMINGO 18:00', 'CULTO ITAPERI (NOITE)',       3),

  ('Itaperi',    '2026-08-19', 'QUARTA 19:30',  'CULTO DA PALAVRA ITAPERI',    4),
  ('Industrial', '2026-08-20', 'QUINTA 19:30',  'CULTO DA PALAVRA INDUSTRIAL', 4),
  ('Industrial', '2026-08-23', 'DOMINGO 10:00', 'CULTO INDUSTRIAL (MANHÃ)',    4),
  ('Industrial', '2026-08-23', 'DOMINGO 17:00', 'CULTO INDUSTRIAL (TARDE)',    4),
  ('Industrial', '2026-08-23', 'DOMINGO 19:00', 'CULTO INDUSTRIAL (NOITE)',    4),
  ('Itaperi',    '2026-08-23', 'DOMINGO 18:00', 'CULTO ITAPERI (NOITE)',       4);

-- Inicializar registros em `schedule` para cada serviço
INSERT INTO public.schedule (service_id, keyboard_member, guitar_member, bass_member, drums_member, vocal_members)
SELECT id, '-', '-', '-', '-', '-' FROM public.services
ON CONFLICT (service_id) DO NOTHING;
